sudo: required
services:
    - docker



before_install:
    
    - docker build -t shahnawaz-khan-pathan/docker-react -f Dockerfile.dev .


script:

    - docker run -e CI=true shahnawaz-khan-pathan/docker-react npm run test


language: generic

